<a href="https://colab.research.google.com/github/taji99/python_basic/blob/master/200723_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 行列と行列積
線形代数は、ベクトルや行列などを扱う数学の分野の一つです。  
ディープラーニングでは多くの数値を扱う必要があるのですが、線形代数を用いれば多くの数値に対する処理を簡潔な数式で記述することができます。  
そして、その数式はNumpyでコードに落とし込むことができます。  
今回は、その初歩として、主に行列と行列積について学びます。

## ●スカラー

スカラー（scalar）は1、5、1.2、-7などの通常の数値のことです。  
本講座では、数式におけるアルファベット、もしくはギリシャ文字の小文字はスカラーを表すものとします。（例: $a$、$p$、$\alpha$、$\gamma$） 

Pythonで扱う通常の数値は、このスカラーに対応します。  
以下はコード上におけるスカラーの例です。

In [1]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5  # 1.2x10の5乗 120000

## ●ベクトル

ベクトルは、スカラーを直線上に並べたものです。  
本コースにおける数式では、アルファベットの小文字に矢印を乗せたものでベクトルを表します。  
以下はベクトルの表記の例です。

$$ \begin{aligned}
\vec{a} & = \left(
    \begin{array}{c}
      1 \\
      2 \\
      3
    \end{array}
 \right) \\
 \vec{b} & = (-2.3, 0.25, -1.2, 1.8, 0.41) \\
 \vec{p} & = \left(
    \begin{array}{c}
      p_1 \\
      p_2 \\
      \vdots \\
      p_m
    \end{array}
 \right) \\
\vec{q} & = (q_1, q_2, \cdots, q_n)
\end{aligned} $$

ベクトルには、上記の$\vec{a}$、$\vec{p}$のように縦に数値を並べる縦ベクトルと、$\vec{b}$、$\vec{q}$のように横に数値を並べる横ベクトルがあります。

ベクトルは、Numpyの1次元配列を用いて以下のように表すことができます。

In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])
print(b)

[1 2 3]
[-2.3   0.25 -1.2   1.8   0.41]


## ●行列

行列はスカラーを格子状に並べたもので、例えば以下のように表記します。

$$
   \left(
    \begin{array}{cccc}
      0.12 & -0.34 & 1.3 & 0.81 \\
      -1.4 & 0.25 & 0.69 & -0.41 \\
      0.25 & -1.5 & -0.15 & 1.1 \\
    \end{array}
  \right)
$$

行列において、水平方向のスカラーの並びを**行**、垂直方向のスカラーの並びを**列**といいます。  

行は、上から1行目、2行目、3行目...と数えます。  
列は、左から1列目、2列目、3列目...と数えます。  
また、行がm個、列がn個並んでいる行列を、m x nの行列と表現します。  
従って、上の図の行列は、3x4の行列になります。  

なお、縦ベクトルは列の数が1の行列と、横ベクトルは行の数が1の行列と考えることもできます。   

本講座における数式では、アルファベット大文字のイタリックで行列を表します。以下は行列の表記の例です。  

$$
   A = \left(
    \begin{array}{cccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
    \end{array}
  \right)
$$
$$
   P = \left(
    \begin{array}{cccc}
      p_{11} & p_{12} & \ldots & p_{1n} \\
      p_{21} & p_{22} & \ldots & p_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      p_{m1} & p_{m2} & \ldots & p_{mn} \\
    \end{array}
  \right) 
$$

行列$A$は2x3の行列で、行列$P$はm x nの行列です。  
また、$P$に見られるように、行列の要素を変数で表す際の添字の数は2つです。    

Numpyの2次元配列を用いると、例えば以下のように行列を表現することができます。  

In [3]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3の行列
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])  # 3x2の行列
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


## ●行列の積

行列積では、前の行列における行の各要素と、後の行列における列の各要素を掛け合わせて総和をとり、新しい行列の要素とします。  

行列積の例を見ていきましょう。  
まず、行列$A$と$B$を次のように設定します。  

$$
   A = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right)
$$ 

$$ 
   B = \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right)
$$ 

$A$は2x3の行列で、$B$は3x2の行列です。  
そして、$A$と$B$の積を次のように表します。

$$ 
   AB = \left(
    \begin{array}{ccc}
      a_{11} & a_{12} & a_{13} \\
      a_{21} & a_{22} & a_{23} \\
    \end{array}
  \right) 
  \left(
    \begin{array}{cc}
      b_{11} & b_{12} \\
      b_{21} & b_{22} \\
      b_{31} & b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31} & a_{11}b_{12}+a_{12}b_{22}+a_{13}b_{32} \\
      a_{21}b_{11}+a_{22}b_{21}+a_{23}b_{31} & a_{21}b_{12}+a_{22}b_{22}+a_{23}b_{32} \\
    \end{array}
  \right) \\
 = \left(
    \begin{array}{ccc}
      \sum\limits_{k=1}^3 a_{1k}b_{k1} & \sum\limits_{k=1}^3 a_{1k}b_{k2} \\
      \sum\limits_{k=1}^3 a_{2k}b_{k1} & \sum\limits_{k=1}^3 a_{2k}b_{k2} \\
    \end{array}
  \right)
$$ 

$A$の各行と$B$の各列の各要素を掛け合わせて総和をとり、新しい行列の各要素とします。  
上記の行列積には総和の記号$\Sigma$が登場していますが、行列積は積の総和を計算する際に大活躍します。  
人工知能では積の総和を頻繁に計算するので、行列積は欠くことができません。 

それでは、試しに数値計算をしてみましょう。以下の行列$A$、$B$を考えます。

$$
   A  = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      1 & 2 & 3 \\
    \end{array}
  \right) \\
   B  = \left(
    \begin{array}{cc}
      2 & 1 \\
      2 & 1 \\
      2 & 1 \\
    \end{array}
  \right) \\
$$ 

これらの行列の行列積は、以下の通りに計算できます。

$$
AB = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      1 & 2 & 3 \\
    \end{array}
  \right) 
  \left(
    \begin{array}{cc}
      2 & 1 \\
      2 & 1 \\
      2 & 1 \\
    \end{array}
  \right) \\
= \left(
    \begin{array}{ccc}
      0\times 2+1\times 2+2\times 2 & 0\times 1+1\times 1+2\times 1 \\
      1\times 2+2\times 2+3\times 2 & 1\times 1+2\times 1+3\times 1 \\
    \end{array}
  \right) \\
= \left(
    \begin{array}{ccc}
      6 & 3 \\
      12 & 6 \\
    \end{array}
  \right)
$$ 

スカラーの積と異なり、行列積においては、前の行列と後ろの行列の交換は特定の条件を除きできません。  
そして、行列積を計算するためには、前の行列の列数と、後ろの行列の行数が一致していなければいけません。  
例えば、前の行列の列数が3であれば、後ろの行列の行数は3である必要があります。 

行列積は、総和を使ってより一般的な形で記述することができます。  
以下は、l x mの行列$A$と、m x nの行列$B$の行列積です。

$$  \begin{aligned} \\
AB & = \left(
    \begin{array}{cc}
      a_{11} & a_{12} & \ldots & a_{1m} \\
      a_{21} & a_{22} & \ldots & a_{2m} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{l1} & a_{l2} & \ldots & a_{lm} \\
    \end{array}
  \right)
\left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn} \\
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{cccc}
      \sum\limits_{k=1}^m a_{1k}b_{k1} & \sum\limits_{k=1}^m a_{1k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{1k}b_{kn} \\
       \sum\limits_{k=1}^m a_{2k}b_{k1} & \sum\limits_{k=1}^m a_{2k}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{2k}b_{kn} \\
      \vdots & \vdots & \ddots & \vdots \\
      \sum\limits_{k=1}^m a_{lk}b_{k1} & \sum\limits_{k=1}^m a_{lk}b_{k2} & \ldots & \sum\limits_{k=1}^m a_{lk}b_{kn} \\
    \end{array}
  \right)
  \end{aligned}
$$

行列積を全ての行と列の組み合わせで計算するのは大変ですが、Numpyのdot関数を用いれば、簡単に行列積を計算することができます。  

In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


## ●要素ごとの積（アダマール積）

行列の要素ごとの積は、アダマール積とも呼ばれており、行列の各要素を掛け合わせます。  
以下の行列$A$、$B$を考えましょう。

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{cccc}
      a_{11} & a_{12} & \ldots & a_{1n} \\
      a_{21} & a_{22} & \ldots & a_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1} & a_{m2} & \ldots & a_{mn}
    \end{array}
  \right) \\
   B & = \left(
    \begin{array}{cccc}
      b_{11} & b_{12} & \ldots & b_{1n} \\
      b_{21} & b_{22} & \ldots & b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      b_{m1} & b_{m2} & \ldots & b_{mn}
    \end{array}
  \right)
\end{aligned} $$ 

これらの行列の要素ごとの積は、演算子$\circ$を用いて次のように表すことができます。

$$
   A\circ B = \left(
    \begin{array}{cccc}
      a_{11}b_{11} & a_{12}b_{12} & \ldots & a_{1n}b_{1n} \\
      a_{21}b_{21} & a_{22}b_{22} & \ldots & a_{2n}b_{2n} \\
      \vdots & \vdots & \ddots & \vdots \\
      a_{m1}b_{m1} & a_{m2}b_{m2} & \ldots & a_{mn}b_{mn}
    \end{array}
  \right)
$$

例えば次ような場合、

$$ \begin{aligned} \\
   A  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      3 & 4 & 5 \\
      6 & 7 & 8
    \end{array}
  \right) \\
  B  & = \left(
    \begin{array}{ccc}
      0 & 1 & 2 \\
      2 & 0 & 1 \\
      1 & 2 & 0
    \end{array}
  \right)
\end{aligned}
$$

$A$と$B$の要素ごとの積は次のようになります。

$$ \begin{aligned} \\
  A\circ B  & = \left(
    \begin{array}{ccc}
      0\times 0 & 1\times 1 & 2\times 2 \\
      3\times 2 & 4\times 0 & 5\times 1 \\
      6\times 1 & 7\times 2 & 8\times 0
    \end{array}
  \right) \\
  & = \left(
    \begin{array}{ccc}
      0 & 1 & 4 \\
      6 & 0 & 5 \\
      6 & 14 & 0
    \end{array}
  \right)
\end{aligned}
$$

要素ごとの積を、Numpyを用いて実装すると、以下のセルのようになります。  
要素ごとの演算にはスカラーの積の演算子`*`を使います。  

In [5]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 
b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


要素ごとの積を計算するためには、配列の形状が同じである必要があります。  
要素ごとの和には`+`、要素ごとの差には`-`、要素ごとの割り算には`/`を使います。

## ●転置

行列に対する重要な操作に、**転置**というものがあります。行列を転置することにより、行と列が入れ替わります。以下は転置の例ですが、例えば行列$A$の転置行列は$A^{\mathrm{T}}$と表します。  

$$  \begin{aligned} \\
   A & = \left(
    \begin{array}{ccc}
      1 & 2 & 3 \\
      4 & 5 & 6 \\
    \end{array}
  \right) \\
   A^{\mathrm{T}} & = \left(
    \begin{array}{cc}
      1 & 4 \\
      2 & 5 \\
      3 & 6 \\
    \end{array}
  \right) \\
\end{aligned} $$ 

$$  \begin{aligned} \\
   B & = \left(
    \begin{array}{cc}
      a & b \\
      c & d \\
      e & f \\
    \end{array}
  \right) \\
   B^{\mathrm{T}} & = \left(
    \begin{array}{ccc}
      a & c & e \\
      b & d & f \\
    \end{array}
  \right) \\
\end{aligned} $$ 

Numpyにおいては、行列を表す配列名の後に`.T`を付けると転置されます。

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.T)  # 転置

[[1 4]
 [2 5]
 [3 6]]
